DOMAIN = "phoenix_ev_charger"
DEFAULT_NAME = "Walli"
DEFAULT_SCAN_INTERVAL = 60
DEFAULT_PORT = 502
DEFAULT_DEVICE_MODEL = "EV-CC-AC1-M3"
CONF_PEVC_HUB = "pevc_hub"
CONF_DEVICE_MODEL = "device_model"
ATTR_MANUFACTURER = "Phoenix Contact"

PHOENIX_DEVICE_VARIANTS = {
    "EV-CC-AC1-M3",
    "EM-CP-PP",
}

SWITCHES = {
    "wallbox": ["wallbox", "mdi:electric-switch", True],
}

BINARY_SENSOR_TYPES = {
    "StatusDigInLD": ["Input LD", "statdiginld", None, "mdi:electric-switch", True],
    "StatusDigInEN": ["Input EN", "statdiginen", None, "mdi:electric-switch", True],
    "StatusDigInML": ["Input ML", "statdiginml", None, "mdi:electric-switch", True],
    "StatusDigInXR": ["Input XR", "statdiginxr", None, "mdi:electric-switch", True],
    "StatusDigInIN": ["Input IN", "statdiginin", None, "mdi:electric-switch", True],
    "StatusDigOutER": ["Output ER", "statdigouter", None, "mdi:led-outline", False],
    "StatusDigOutLR": ["Output LR", "statdigoutlr", None, "mdi:led-outline", False],
    "StatusDigOutVR": ["Output VR", "statdigoutvr", None, "mdi:led-outline", False],
    "StatusDigOutCR": ["Output CR", "statdigoutcr", None, "mdi:led-outline", False],
}

SENSOR_TYPES = {
    "DeviceState": ["Device State", "devstate", None, "mdi:ev-station"],
    "EnergyChargeSequence": ["Energy Charge Sequence", "chargesequence", "Wh", "mdi:counter"],
    "ActualChargeCurrentSetting": ["Actual Charge Current Setting", "chargecurrentsetting", "A",  "mdi:current-ac"],
    "RemoteChargeCurrentLimitation": ["Remote Charge Current Limitation", "remotechargecurrentlimit", "A",
                                      "mdi:current-ac"],
    "CableAssemblyCapability": ["Capability of Cable Assembly", "cablecapability", "A",
                                "mdi:current-ac"],
    "ActiveChargingDuration": ["Active Charging Duration", "chargingduration", "h", "mdi:clock-start"],
    "DigInLD": ["Input LD", "diginld", None, "mdi:wrench-outline"],
    "DigInEN": ["Input EN", "diginen", None, "mdi:wrench-outline"],
    "DigInML": ["Input ML", "diginml", None, "mdi:wrench-outline"],
    "DigInXR": ["Input XR", "diginxr", None, "mdi:wrench-outline"],
    "DigInIN": ["Input IN", "diginin", None, "mdi:wrench-outline"],
    "DigOutER": ["Output ER", "digouter", None, "mdi:wrench-outline"],
    "DigOutLR": ["Output LR", "digoutlr", None, "mdi:wrench-outline"],
    "DigOutVR": ["Output VR", "digoutvr", None, "mdi:wrench-outline"],
    "DigOutCR": ["Output CR", "digoutcr", None, "mdi:wrench-outline"],
    "DeviceName": ["Device name", "devicename", None, "mdi:identifier"],
    "MacAddress": ["MAC address", "macaddress", None, "mdi:network-outline"],
    "SerialNumber": ["Serial Number", "serialnr", None, "mdi:textbox-outline"],
    "FirmwareVersion": ["Firmware version", "fwvers", None, None],
}

DEVICE_STATUSSES = {
    '0': "offline",
    'A': "No car connected - State A",
    'B': "Car connected - State B",
    'C': "Charging possible - State C",
    'D': "Errorstate D",
    'E': "Errorstate E",
}

DIGITAL_OUT_FUNCTIONS = {
    0:  "Inaktiv",
    1:  "Ladesteuerung im Status A",
    2:  "Ladesteuerung im Status B",
    3:  "Ladesteuerung im Status B und PWM EIN",
    4:  "Ladesteuerung im Status B und PWM AUS",
    5:  "Ladesteuerung im Status C",
    6:  "Ladesteuerung im Status D",
    7: "Ladesteuerung im Status E",
    8: "Ladesteuerung im Status F",
    9: "Ladesteuerung im Status A oder B",
    10: "Ladesteuerung im Status A oder B und PWM EIN",
    11: "Ladesteuerung im Status A oder B und PWM AUS",
    12: "Ladesteuerung im Status A, B oder C",
    13: "Ladesteuerung im Status A, B oder D",
    14: "Ladesteuerung im Status A bis D",
    15: "Ladesteuerung im Status E oder F (Default für Ausgang ER)",
    16: "Ladesteuerung im Status C oder D (Default für Ausgang VR)",
    17: "PWM EIN (Default für Ausgang CR)",
    18: "Gültiger Proximity erkannt",
    19: "Ungültiger Proximity erkannt",
    20: "13-A-Ladestecker erkannt",
    21: "20-A-Ladestecker erkannt",
    22: "32-A-Ladestecker erkannt",
    23: "63-A-Ladestecker erkannt",
    24: "13-A- oder 20-A-Ladestecker erkannt",
    25: "13-A-, 20-A- oder 32-A-Ladestecker erkannt",
    26: "Ladestecker mit geringer Stromtragfähigkeit abgewiesen",
    27: "Ladesteuerung schaltet das Ladeschütz EIN",
    28: "Status D Belüftung an",
    29: "Verriegelung aktiv (Default für Ausgang LR)",
    30: "Register Ausgang 1",
    31: "Register Ausgang 2",
    32: "Register Ausgang 3",
    33: "Register Ausgang 4",
    34: "Überstrom detektiert",
    35: "Ladeschützüberwachung ausgelöst",
    36: "Status D, Fahrzeug abgewiesen",
    37: "Fahrzeug angeschlossen im Status B oder C oder D",
    38: "Reserviert für zukünftige Funktion",
    39: "Autorisierungsstatus (Blinken: Autorisierung in Arbeit, Permanent: Freigabe liegt vor)",
    0x29: "Status A oder B1 Authorisierung Blinken",
}

DIGITAL_IN_FUNCTIONS = {
    0: "Inaktiv",
    1: "Freigabe Ladevorgang permanentes High-Signal (Default für Eingang EN)",
    2: "Verfügbarkeit Ladestation (Default für Eingang XR)",
    3: "Rückmeldung Verriegelung Ladestecker (Default für Eingang LD)",
    4: "Verriegelung (permanentes High-Signal)",
    5: "Schützüberwachung über NO-Hilfskontakt",
    6: "Schützüberwachung über NC-Hilfskontakt",
    7: "PWM-Signal auf 5 %",
    8: "Ladestrom auf 6 A",
    9: "Ladestrom auf 10 A",
    10: "Ladestrom auf 13 A",
    11: "Ladestrom auf 16 A (Default für Eingang IN)",
    12: "Ladestrom auf 20 A",
    13: "Ladestrom auf 32 A",
    14: "Ladestrom auf 63 A",
    15: "Ladestrom auf 70 A",
    16: "Freigabe Ladevorgang gepulstes Signal",
    17: "Verriegelung (gepulstes Signal) (Default für Eingang ML)",
    18: "Reserviert für zukünftige Funktion",
    19: "Ladestrom auf zulässigen Maximalwert",
    20: "Ladevorgang pausieren (OCPP: Suspend EVSE)",
    21: "Fehlerzustand erzeugen",
}

EN_DIGITAL_OUT_FUNCTIONS = {
    0: "Inactive",
    1: "Charging controller in status A",
    2: "Charging controller in status B",
    3: "Charging controller in status B and PWM ON",
    4: "Charging controller in status B and PWM OFF",
    5: "Charging controller in status C",
    6: "Charging controller in status D",
    7: "Charging controller in status E",
    8: "Charging controller in status F",
    9: "Charging controller in status A or B",
    10: "Charging controller in status A or B and PWM ON",
    11: "Charging controller in status A or B and PWM OFF",
    12: "Charging controller in status A, B or C",
    13: "Charging controller in status A, B or D",
    14: "Charging controller in status A to D",
    15: "Charging controller in status E or F (default for output ER)",
    16: "Charging controller in status C or D (default for output VR)",
    17: "PWM ON (default for output CR)",
    18: "Valid Proximity detected",
    19: "Invalid Proximity detected",
    20: "13 A charging connector detected",
    21: "20 A charging connector detected",
    22: "32 A charging connector detected",
    23: "63 A charging connector detected",
    24: "13 A or 20 A charging connector detected",
    25: "13 A, 20 A or 32 A charging connector detected",
    26: "Charging connector with low current carrying capacity rejected",
    27: "Charging controller switches charging contactor ON",
    28: "Status D ventilation on",
    29: "Locking active (default for output LR)",
    30: "Output 1 register",
    31: "Output 2 register",
    32: "Output 3 register",
    33: "Output 4 register",
    34: "Overcurrent detected",
    35: "Charging contactor monitoring triggered",
    36: "Status D, vehicle rejected",
    37: "Vehicle connected in status B or C or D",
    38: "Reserved for future function",
    39: "Authorization status (flashing: authorization in progress, permanent: enable issued)",
    0x29: "State A or B1 Authorize Blink",
}

EN_DIGITAL_IN_FUNCTIONS = {
    0: "Inactive",
    1: "Enable charging process by permanent High signal (default for input EN)",
    2: "Charging station availability (default for input XR)",
    3: "Charging connector locking feedback (default for input LD)",
    4: "Locking (permanent High signal)",
    5: "Contactor monitoring via N/O auxiliary contact",
    6: "Contactor monitoring via N/C auxiliary contact",
    7: "PWM signal at 5%",
    8: "Charging current at 6 A",
    9: "Charging current at 10 A",
    10: "Charging current at 13 A",
    11: "Charging current at 16 A (default for input IN)",
    12: "Charging current at 20 A",
    13: "Charging current at 32 A",
    14: "Charging current at 63 A",
    15: "Charging current at 70 A",
    16: "Enable charging process by pulsed signal",
    17: "Locking (pulsed signal) (default for input ML)",
    18: "Reserved for future function",
    19: "Charging current at maximum permissible value",
    20: "Pause charging process (OCPP: Suspend EVSE)",
    21: "Generate error state",
}

DIGITAL_STATUS = {
    False: "Off",
    True: "On",
}

DATA_UPDATED = "phoenixev_{}_data_updated"